### ISSUE TITLE
Implement user-signing-in function

### ISSUE THREAD

**Issue by tmysok** [tmysok/Protospace#9]
# ABOUT
This issue is a list of tasks that concern `Protospace` 's user function.
The function is roughly divided into 3 parts below.
- Account Creation
- Users' Information Showing
- Users' Information Editing

# ADDITIONAL POINTS
- Implement user function
  - Implement user-signing-in function
    - [x] Install `Devise`
    - [x] Generate view files
    - [x] Configure `Devise` 's validation
    - [x] Localize `Devise`
  - Implement user-info-showing and user-info-editing function
    - [x] Generate Users controller
    - [x] Define `users#show` , `users#edit` and `users#update`
    - [x] Generate view files

**Comment by sa-inu** [comment]
You don't have to write so much in detail!
It is sufficient to the second hierarchy.

**Comment by sa-inu** [comment]
But great! :)

**Comment by tmysok** [comment]
Thank you very much!

well... I didn't know how much I should write and wrote too many...
I will simplify this issue though I know it isn't urgent nor absolutely needed :)

**Comment by tmysok** [comment]
Simplified!
too simple?
Of course I hold previous vesion

**Comment by sa-inu** [comment]
Only one more, change first and second tiers checkboxes to normal lists.

**Comment by tmysok** [comment]
Modified

**Comment by sa-inu** [comment]
Thx!

**Comment by tmysok** [comment]
ユーザー機能の実装は一旦完了ということで良いですか？

**Comment by sa-inu** [comment]
おけ！

**Comment by sa-inu** [comment]
issueをcloseしちゃっていいよ！
次のissue立てておいて！

**Comment by tmysok** [comment]
ありがとうございます！
進みますー
